const ReportPegadaianCicil = {
  headers: [
    "tgl_trx",
    "no_kredit",
    "reff_switching",
    "reff_biller",
    "client_id",
    "kode_produk",
    "jenis_trx",
    "amount",
    "admin",
    "fee",
    "settlement",
    "flag_rekon",
  ],
  mappings: {
    tgl_trx: "feResponse.data.tglTransaksi",
    no_kredit: "feRequest.noIdentitas",
    reff_switching: "feRequest.reffSwitching",
    reff_biller: "feRequest.reffBiller",
    client_id: "feRequest.clientId",
    kode_produk: (jsonData) => getKodeProduk(jsonData),
    jenis_trx: "feRequest.jenisTransaksi",
    amount: "feResponse.data.nominalUangMuka",
    admin: "feResponse.data.administrasi",
    fee: (jsonData) => toIntegerString(getValueFromPath(jsonData, "feResponse.feeAmount")),
    settlement: (jsonData) => toIntegerString(getValueFromPath(jsonData, "esb.creditAmount")),
    flag_rekon: "MA",
  },
};